import Head from "next/head";
import Image from "next/image";
// import Script from 'next/Script'
import styles from "../styles/Home.module.css";
// import styles1 from "../styles/Home1.module.css";
// import styles2 from "../styles/Home2.module.css";
// import Dummy from "./components/dummy";

export default function Home() {
  return (
    <div className={styles.container}>
          {/* <Dummy/>

      <style jsx>
        {
          `.mySpan{color:red}`
        }
      </style> */}
      <style jsx>
        {`{
          h2{font-size:38px}
        }
         {
          h3{font-size:28px}
        }`}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs,huntingcoder blog, hunting coder"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='./sc.js' strategy="lazyOnload"> </Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
         <span className="mySpan dummy">Hunting Coder</span> 
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
        </h1>
        <div className={styles.imagewrapper}>
        <Image className={styles.myImg} src="/Homeimg.avif" width={237} height={158}/></div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
          {/* Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code> */}
        </p>

        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        <div className="blogs">
          <div className="blogItem">
            <h2>Latest Blogs</h2>
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}
